#!/bin/bash

# todo: get it from the configure.ac
# AC_INIT(Gauche, 0.9.4_pre3, shiro@acm.org)
#$(gauche-config -V|sed -e 's/_/-/');
GAUCHE_VERSION=0.9.4-pre3

cat debian/control.in | sed -e "s/@GAUCHE_VERSION@/${GAUCHE_VERSION}/g" >debian/control

for pkg in gauche-dev gauche-doc gauche-gdbm gauche-zlib gauche;
do
    mv -v debian/$pkg.install  debian/gauche-${GAUCHE_VERSION}${pkg#gauche}.install
done


./DIST gen
