#!/bin/bash

# todo: get it from the configure.ac
# AC_INIT(Gauche, 0.9.4_pre3, shiro@acm.org)
#$(gauche-config -V|sed -e 's/_/-/');

GAUCHE_VERSION=""
# "-0.9.14"

cat debian/control.in | sed -e "s/@GAUCHE_VERSION@/${GAUCHE_VERSION}/g" >debian/control

if false
then
    for pkg in gauche-dev gauche-doc gauche-gdbm gauche-zlib gauche;
    do
        # note that we remove "gauche" from 2 different templates:  gauche and gauche-xxx
        mv -v debian/$pkg.install  debian/gauche${GAUCHE_VERSION}${pkg#gauche}.install
    done

    mv -v debian/libgauche0.install  debian/libgauche0${GAUCHE_VERSION}.install
fi

./DIST gen
